### ISSUE TITLE
Missing the Required Plugins

### ISSUE THREAD

**Issue by agileandy** [Assblastois/Obsidian-Vault-Project-Management#1]
Congratulations on the great plugin...

To help people who might want to run this 'straight out of the box', it might be useful to ensure your sample vault includes all the required plugins.

I had to manually install and set these up.

**Comment by Assblastois** [comment]
Hey @agileandy , I downloaded it again, to try to replicate that error, but couldn't. Every plugin should be downloaded automatically as I intended. Was there a specific one missing or was it all of them? 
If you have downloaded them manually, have you also added the QuickAdd macros manually? 
 
Sorry in any case you had to download them manually. If you have any further questions, just ask!
-AB
